type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  accessibilitySettings: String
}

type Project @table {
  name: String!
  code: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
  isPublic: Boolean
  circuitDiagramText: String
  user: User
}

type Tutorial @table {
  title: String!
  content: String!
  createdAt: Timestamp!
  exampleCode: String
  difficultyLevel: String
  tags: [String]
  user: User
}

type Device @table {
  serialNumber: String!
  nickname: String!
  createdAt: Timestamp!
  lastConnectedAt: Timestamp
  firmwareVersion: String
  user: User
}